verbose: false
instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes: ['node_modules/', 'test/']
    compact: false
reporting:
    root: ./coverage
    print: summary
    reports:
        - json
    dir: ./coverage
    report-config:
      json:
        file: coverage.json
    watermarks:
        statements: [90, 99]
        lines: [90, 99]
        functions: [90, 99]
        branches: [90, 99]
